# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'SDKExample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
    pod 'HEREMapsStarter'
    pod 'DropDown'
    pod 'Alamofire', '~>4.7'
    pod 'MBProgressHUD', '~>1.1.0'
  # Pods for SDKExample

end
