# Uncomment the next line to define a global platform for your project
 platform :ios, '8.0'

target 'SqimiTemplate' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
pod 'Font-Awesome-Swift', '~>1.7.2'

  # Pods for SqimiTemplate

end
